[2022-11-22 14:25:46,503] - log.py] - INFO: ---测试开始----
[2022-11-22 14:25:46,503] - log.py] - INFO: 操作步骤1,2,3
[2022-11-22 14:25:46,503] - log.py] - WARNING: ----测试结束----
[2022-11-22 14:30:53,186] - log.py] - INFO: ---测试开始----
[2022-11-22 14:30:53,186] - log.py] - INFO: 操作步骤1,2,3
[2022-11-22 14:30:53,186] - log.py] - WARNING: ----测试结束----
[2022-11-22 14:30:59,529] - log.py] - INFO: 日志log
[2022-11-22 14:30:59,700] - log.py] - INFO: 日志log
[2022-11-22 14:45:59,166] - log.py] - ERROR: 发生error
[2022-11-22 14:47:24,983] - log.py] - ERROR: list index out of range
[2022-11-22 14:47:56,014] - log.py] - ERROR: list index out of range
[2022-11-22 14:49:09,142] - log.py] - ERROR: list index out of range
[2022-11-22 14:51:18,423] - log.py] - ERROR: list index out of range
[2022-11-22 14:51:45,716] - log.py] - ERROR: list index out of range
[2022-11-22 14:52:05,401] - log.py] - ERROR: list index out of range
[2022-11-22 14:54:07,677] - log.py] - ERROR: list index out of range
[2022-11-22 14:54:56,589] - log.py] - ERROR: list index out of range
[2022-11-22 14:55:15,923] - log.py] - INFO: 日志log
[2022-11-22 14:55:15,971] - log.py] - INFO: 日志log
[2022-11-22 14:57:07,020] - log.py] - INFO: 查询教室testcase
[2022-11-22 14:57:07,336] - log.py] - INFO: 查询教室testcase
[2022-11-22 14:57:50,179] - log.py] - INFO: 查询教室testcase
[2022-11-22 14:57:50,261] - log.py] - INFO: 查询教室testcase
[2022-11-22 14:59:28,521] - log.py] - INFO: 查询教室testcase
[2022-11-22 14:59:28,701] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:00:10,544] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:00:10,624] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:19:27,039] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:19:27,128] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:24:37,848] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:24:37,939] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:26:07,303] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:26:07,365] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:27:07,752] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:27:07,854] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:27:08,407] - log.py] - ERROR: assert False == True
[2022-11-22 15:27:08,463] - log.py] - ERROR: assert False == True
[2022-11-22 15:46:34,989] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:46:35,059] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:46:35,396] - log.py] - ERROR: [Errno Expecting value] <html>
<head>
    <title>Charles Error Report</title>
    <style type="text/css">
body {
    font-family: Arial,Helvetica,Sans-serif;
    font-size: 12px;
    color: #333333;
    background-color: #ffffff;
}

h1 {
    font-size: 24px;
    font-weight: bold;
}

h2 {
    font-size: 18px;
    font-weight: bold;
}
    </style>
</head>
<body>

<h1>Charles Error Report</h1>
<h2>Failed to connect to remote host</h2>
<p>Charles failed to connect to the remote host. Check that your Internet connection is ok and that the remote host is accessible. Maybe your network uses a proxy server to access the Internet? You can configure Charles to use an external proxy server in the External Proxy Settings.</p>
<p>The actual exception reported was:</p>
<pre>
java.net.ConnectException: Connection refused (Connection refused)
</pre>

<p>
<i>Charles Proxy, <a href="https://www.charlesproxy.com/">https://www.charlesproxy.com/</a></i>
</p>
</body>
</html>: 0
[2022-11-22 15:46:35,468] - log.py] - ERROR: [Errno Expecting value] <html>
<head>
    <title>Charles Error Report</title>
    <style type="text/css">
body {
    font-family: Arial,Helvetica,Sans-serif;
    font-size: 12px;
    color: #333333;
    background-color: #ffffff;
}

h1 {
    font-size: 24px;
    font-weight: bold;
}

h2 {
    font-size: 18px;
    font-weight: bold;
}
    </style>
</head>
<body>

<h1>Charles Error Report</h1>
<h2>Failed to connect to remote host</h2>
<p>Charles failed to connect to the remote host. Check that your Internet connection is ok and that the remote host is accessible. Maybe your network uses a proxy server to access the Internet? You can configure Charles to use an external proxy server in the External Proxy Settings.</p>
<p>The actual exception reported was:</p>
<pre>
java.net.ConnectException: Connection refused (Connection refused)
</pre>

<p>
<i>Charles Proxy, <a href="https://www.charlesproxy.com/">https://www.charlesproxy.com/</a></i>
</p>
</body>
</html>: 0
[2022-11-22 15:46:35,489] - log.py] - ERROR: [Errno Expecting value] <html>
<head>
    <title>Charles Error Report</title>
    <style type="text/css">
body {
    font-family: Arial,Helvetica,Sans-serif;
    font-size: 12px;
    color: #333333;
    background-color: #ffffff;
}

h1 {
    font-size: 24px;
    font-weight: bold;
}

h2 {
    font-size: 18px;
    font-weight: bold;
}
    </style>
</head>
<body>

<h1>Charles Error Report</h1>
<h2>Failed to connect to remote host</h2>
<p>Charles failed to connect to the remote host. Check that your Internet connection is ok and that the remote host is accessible. Maybe your network uses a proxy server to access the Internet? You can configure Charles to use an external proxy server in the External Proxy Settings.</p>
<p>The actual exception reported was:</p>
<pre>
java.net.ConnectException: Connection refused (Connection refused)
</pre>

<p>
<i>Charles Proxy, <a href="https://www.charlesproxy.com/">https://www.charlesproxy.com/</a></i>
</p>
</body>
</html>: 0
[2022-11-22 15:46:35,596] - log.py] - ERROR: [Errno Expecting value] <html>
<head>
    <title>Charles Error Report</title>
    <style type="text/css">
body {
    font-family: Arial,Helvetica,Sans-serif;
    font-size: 12px;
    color: #333333;
    background-color: #ffffff;
}

h1 {
    font-size: 24px;
    font-weight: bold;
}

h2 {
    font-size: 18px;
    font-weight: bold;
}
    </style>
</head>
<body>

<h1>Charles Error Report</h1>
<h2>Failed to connect to remote host</h2>
<p>Charles failed to connect to the remote host. Check that your Internet connection is ok and that the remote host is accessible. Maybe your network uses a proxy server to access the Internet? You can configure Charles to use an external proxy server in the External Proxy Settings.</p>
<p>The actual exception reported was:</p>
<pre>
java.net.ConnectException: Connection refused (Connection refused)
</pre>

<p>
<i>Charles Proxy, <a href="https://www.charlesproxy.com/">https://www.charlesproxy.com/</a></i>
</p>
</body>
</html>: 0
[2022-11-22 15:47:18,483] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:47:18,565] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:47:18,763] - log.py] - ERROR: [Errno Expecting value] <html>
<head>
    <title>Charles Error Report</title>
    <style type="text/css">
body {
    font-family: Arial,Helvetica,Sans-serif;
    font-size: 12px;
    color: #333333;
    background-color: #ffffff;
}

h1 {
    font-size: 24px;
    font-weight: bold;
}

h2 {
    font-size: 18px;
    font-weight: bold;
}
    </style>
</head>
<body>

<h1>Charles Error Report</h1>
<h2>Failed to connect to remote host</h2>
<p>Charles failed to connect to the remote host. Check that your Internet connection is ok and that the remote host is accessible. Maybe your network uses a proxy server to access the Internet? You can configure Charles to use an external proxy server in the External Proxy Settings.</p>
<p>The actual exception reported was:</p>
<pre>
java.net.ConnectException: Connection refused (Connection refused)
</pre>

<p>
<i>Charles Proxy, <a href="https://www.charlesproxy.com/">https://www.charlesproxy.com/</a></i>
</p>
</body>
</html>: 0
[2022-11-22 15:47:18,774] - log.py] - ERROR: [Errno Expecting value] <html>
<head>
    <title>Charles Error Report</title>
    <style type="text/css">
body {
    font-family: Arial,Helvetica,Sans-serif;
    font-size: 12px;
    color: #333333;
    background-color: #ffffff;
}

h1 {
    font-size: 24px;
    font-weight: bold;
}

h2 {
    font-size: 18px;
    font-weight: bold;
}
    </style>
</head>
<body>

<h1>Charles Error Report</h1>
<h2>Failed to connect to remote host</h2>
<p>Charles failed to connect to the remote host. Check that your Internet connection is ok and that the remote host is accessible. Maybe your network uses a proxy server to access the Internet? You can configure Charles to use an external proxy server in the External Proxy Settings.</p>
<p>The actual exception reported was:</p>
<pre>
java.net.ConnectException: Connection refused (Connection refused)
</pre>

<p>
<i>Charles Proxy, <a href="https://www.charlesproxy.com/">https://www.charlesproxy.com/</a></i>
</p>
</body>
</html>: 0
[2022-11-22 15:47:18,782] - log.py] - ERROR: [Errno Expecting value] <html>
<head>
    <title>Charles Error Report</title>
    <style type="text/css">
body {
    font-family: Arial,Helvetica,Sans-serif;
    font-size: 12px;
    color: #333333;
    background-color: #ffffff;
}

h1 {
    font-size: 24px;
    font-weight: bold;
}

h2 {
    font-size: 18px;
    font-weight: bold;
}
    </style>
</head>
<body>

<h1>Charles Error Report</h1>
<h2>Failed to connect to remote host</h2>
<p>Charles failed to connect to the remote host. Check that your Internet connection is ok and that the remote host is accessible. Maybe your network uses a proxy server to access the Internet? You can configure Charles to use an external proxy server in the External Proxy Settings.</p>
<p>The actual exception reported was:</p>
<pre>
java.net.ConnectException: Connection refused (Connection refused)
</pre>

<p>
<i>Charles Proxy, <a href="https://www.charlesproxy.com/">https://www.charlesproxy.com/</a></i>
</p>
</body>
</html>: 0
[2022-11-22 15:47:18,877] - log.py] - ERROR: [Errno Expecting value] <html>
<head>
    <title>Charles Error Report</title>
    <style type="text/css">
body {
    font-family: Arial,Helvetica,Sans-serif;
    font-size: 12px;
    color: #333333;
    background-color: #ffffff;
}

h1 {
    font-size: 24px;
    font-weight: bold;
}

h2 {
    font-size: 18px;
    font-weight: bold;
}
    </style>
</head>
<body>

<h1>Charles Error Report</h1>
<h2>Failed to connect to remote host</h2>
<p>Charles failed to connect to the remote host. Check that your Internet connection is ok and that the remote host is accessible. Maybe your network uses a proxy server to access the Internet? You can configure Charles to use an external proxy server in the External Proxy Settings.</p>
<p>The actual exception reported was:</p>
<pre>
java.net.ConnectException: Connection refused (Connection refused)
</pre>

<p>
<i>Charles Proxy, <a href="https://www.charlesproxy.com/">https://www.charlesproxy.com/</a></i>
</p>
</body>
</html>: 0
[2022-11-22 15:47:34,923] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:47:34,996] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:47:35,124] - log.py] - ERROR: [Errno Expecting value] <html>
<head>
    <title>Charles Error Report</title>
    <style type="text/css">
body {
    font-family: Arial,Helvetica,Sans-serif;
    font-size: 12px;
    color: #333333;
    background-color: #ffffff;
}

h1 {
    font-size: 24px;
    font-weight: bold;
}

h2 {
    font-size: 18px;
    font-weight: bold;
}
    </style>
</head>
<body>

<h1>Charles Error Report</h1>
<h2>Failed to connect to remote host</h2>
<p>Charles failed to connect to the remote host. Check that your Internet connection is ok and that the remote host is accessible. Maybe your network uses a proxy server to access the Internet? You can configure Charles to use an external proxy server in the External Proxy Settings.</p>
<p>The actual exception reported was:</p>
<pre>
java.net.ConnectException: Connection refused (Connection refused)
</pre>

<p>
<i>Charles Proxy, <a href="https://www.charlesproxy.com/">https://www.charlesproxy.com/</a></i>
</p>
</body>
</html>: 0
[2022-11-22 15:47:35,140] - log.py] - ERROR: [Errno Expecting value] <html>
<head>
    <title>Charles Error Report</title>
    <style type="text/css">
body {
    font-family: Arial,Helvetica,Sans-serif;
    font-size: 12px;
    color: #333333;
    background-color: #ffffff;
}

h1 {
    font-size: 24px;
    font-weight: bold;
}

h2 {
    font-size: 18px;
    font-weight: bold;
}
    </style>
</head>
<body>

<h1>Charles Error Report</h1>
<h2>Failed to connect to remote host</h2>
<p>Charles failed to connect to the remote host. Check that your Internet connection is ok and that the remote host is accessible. Maybe your network uses a proxy server to access the Internet? You can configure Charles to use an external proxy server in the External Proxy Settings.</p>
<p>The actual exception reported was:</p>
<pre>
java.net.ConnectException: Connection refused (Connection refused)
</pre>

<p>
<i>Charles Proxy, <a href="https://www.charlesproxy.com/">https://www.charlesproxy.com/</a></i>
</p>
</body>
</html>: 0
[2022-11-22 15:47:35,225] - log.py] - ERROR: [Errno Expecting value] <html>
<head>
    <title>Charles Error Report</title>
    <style type="text/css">
body {
    font-family: Arial,Helvetica,Sans-serif;
    font-size: 12px;
    color: #333333;
    background-color: #ffffff;
}

h1 {
    font-size: 24px;
    font-weight: bold;
}

h2 {
    font-size: 18px;
    font-weight: bold;
}
    </style>
</head>
<body>

<h1>Charles Error Report</h1>
<h2>Failed to connect to remote host</h2>
<p>Charles failed to connect to the remote host. Check that your Internet connection is ok and that the remote host is accessible. Maybe your network uses a proxy server to access the Internet? You can configure Charles to use an external proxy server in the External Proxy Settings.</p>
<p>The actual exception reported was:</p>
<pre>
java.net.ConnectException: Connection refused (Connection refused)
</pre>

<p>
<i>Charles Proxy, <a href="https://www.charlesproxy.com/">https://www.charlesproxy.com/</a></i>
</p>
</body>
</html>: 0
[2022-11-22 15:47:35,322] - log.py] - ERROR: [Errno Expecting value] <html>
<head>
    <title>Charles Error Report</title>
    <style type="text/css">
body {
    font-family: Arial,Helvetica,Sans-serif;
    font-size: 12px;
    color: #333333;
    background-color: #ffffff;
}

h1 {
    font-size: 24px;
    font-weight: bold;
}

h2 {
    font-size: 18px;
    font-weight: bold;
}
    </style>
</head>
<body>

<h1>Charles Error Report</h1>
<h2>Failed to connect to remote host</h2>
<p>Charles failed to connect to the remote host. Check that your Internet connection is ok and that the remote host is accessible. Maybe your network uses a proxy server to access the Internet? You can configure Charles to use an external proxy server in the External Proxy Settings.</p>
<p>The actual exception reported was:</p>
<pre>
java.net.ConnectException: Connection refused (Connection refused)
</pre>

<p>
<i>Charles Proxy, <a href="https://www.charlesproxy.com/">https://www.charlesproxy.com/</a></i>
</p>
</body>
</html>: 0
[2022-11-22 15:48:08,900] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:48:09,009] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:48:10,404] - log.py] - ERROR: HTTPConnectionPool(host='10.2.128.204', port=8081): Max retries exceeded with url: /web/api/v1/type/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102243a90>: Failed to establish a new connection: [Errno 61] Connection refused'))
[2022-11-22 15:48:10,415] - log.py] - ERROR: HTTPConnectionPool(host='10.2.128.204', port=8081): Max retries exceeded with url: /web/api/v1/type/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10226d5e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[2022-11-22 15:48:10,420] - log.py] - ERROR: HTTPConnectionPool(host='10.2.128.204', port=8081): Max retries exceeded with url: /web/api/v1/type/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102264c40>: Failed to establish a new connection: [Errno 61] Connection refused'))
[2022-11-22 15:48:10,611] - log.py] - ERROR: HTTPConnectionPool(host='10.2.128.204', port=8081): Max retries exceeded with url: /web/api/v1/classRoom/list (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1024aa130>: Failed to establish a new connection: [Errno 61] Connection refused'))
[2022-11-22 15:48:28,580] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:48:28,686] - log.py] - INFO: 查询教室testcase
[2022-11-22 15:48:29,081] - log.py] - ERROR: HTTPConnectionPool(host='10.2.128.204', port=8081): Max retries exceeded with url: /web/api/v1/type/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102dd88e0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[2022-11-22 15:48:29,100] - log.py] - ERROR: HTTPConnectionPool(host='10.2.128.204', port=8081): Max retries exceeded with url: /web/api/v1/type/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102e92640>: Failed to establish a new connection: [Errno 61] Connection refused'))
[2022-11-22 15:48:29,112] - log.py] - ERROR: HTTPConnectionPool(host='10.2.128.204', port=8081): Max retries exceeded with url: /web/api/v1/type/save (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102e82dc0>: Failed to establish a new connection: [Errno 61] Connection refused'))
[2022-11-22 15:48:29,345] - log.py] - ERROR: HTTPConnectionPool(host='10.2.128.204', port=8081): Max retries exceeded with url: /web/api/v1/classRoom/list (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x103861130>: Failed to establish a new connection: [Errno 61] Connection refused'))
